name: kalium_wallet_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 2.0.0+38

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Securley store data in a keystore
  flutter_secure_storage:
    git:
      url: https://github.com/mogol/flutter_secure_storage.git
      ref: develop

  # Nano core functions
  flutter_nano_core: ^1.0.2

  # Shared prefs
  shared_preferences: ^0.4.3

  # Flare for animations
  flare_flutter: ^1.2.2

  # Websockets
  web_socket_channel: ^1.0.9

  # Platform-specific build info
  package_info: ^0.3.2+1

  # Device-specific info
  device_info: ^0.3.0

  # JSON Serialization
  json_annotation: ^2.0.0

  # Localization
  intl: ^0.15.7

  # BigDecimal alternative
  decimal: ^0.3.3

  # Logger
  logging: ^0.11.3+2

  # Native webview plugin
  flutter_webview_plugin: ^0.3.0+2

  # SQLite
  sqflite: ^1.0.0

  # Android/iOS path provider
  path_provider: ^0.4.1

  # TouchID/FaceID
  local_auth:
    git:
      url: https://github.com/bbedward/plugins.git
      path: packages/local_auth
      ref: master

  # Eventbus
  event_taxi: ^0.1.5

  # SVG
  flutter_svg: ^0.10.3
    
  # QR Codes
  qr_flutter: ^1.1.6 # Generator
  barcode_scan:
    git:
      url: https://github.com/bbedward/flutter_barcode_reader.git
      ref: master

  # Share files
  share:
    git:
      url: https://github.com/pboos/plugins.git
      path: packages/share
      ref: feature/shareFile

  # File picker
  file_picker: 1.1.1

  # Deep link support
  uni_links: ^0.1.4

  # HTTP client
  http: ^0.12.0+1

  # Vibrate
  vibrate:
    git:
      url: https://github.com/bbedward/flutter_vibrate.git
      ref: master

  # Toast
  oktoast: ^2.1.5

  # Push notifications - TODO update to newer androidX version
  firebase_messaging: ^ 2.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.1.3
  json_serializable: ^2.0.1
  intl_translation: ^0.17.2

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
          weight: 600
        - asset: fonts/NunitoSans-ExtraLight.ttf
          weight: 100
        - asset: fonts/NunitoSans-Light.ttf
          weight: 200
        - asset: fonts/NunitoSans-SemiBold.ttf
          weight: 700
        - asset: fonts/NunitoSans-Bold.ttf
          weight: 800
        - asset: fonts/NunitoSans-ExtraBold.ttf
          weight: 900
    - family: OverpassMono
      fonts:
        - asset: fonts/OverpassMono-Regular.ttf
          weight: 600
        - asset: fonts/OverpassMono-Light.ttf
          weight: 100
    - family:  AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf
          weight: 500
    - family: NeueHansKendrick
      fonts:
        - asset: fonts/NeueHansKendrick-Medium.ttf
          weight: 600
        - asset: fonts/NeueHansKendrick-Regular.ttf
          weight: 500
        - asset: fonts/NeueHansKendrick-Light.ttf
          weight: 300
     
  assets:
    - assets/monkeyQR.svg
    - assets/welcome_animation.flr
    - assets/welcome_animation_bananasonly.flr
    - assets/welcome_animation_monkeysonly.flr
    - assets/send_animation.flr
    - assets/send_animation_bananasonly.flr
    - assets/send_animation_shadowsonly.flr
    - assets/transfer_animation.flr
    - assets/transfer_animation_kaliumwalletonly.flr
    - assets/transfer_animation_paperwalletonly.flr
    - assets/searchseedqr_animation.flr
    - assets/searchseedqr_animation_magnifyingglassonly.flr
    - assets/searchseedqr_animation_glassonly.flr
    - assets/searchseedqr_animation_qronly.flr
    - assets/searchseedmanual_animation.flr
    - assets/searchseedmanual_animation_magnifyingglassonly.flr
    - assets/searchseedmanual_animation_glassonly.flr
    - assets/searchseedmanual_animation_seedonly.flr
    - assets/threedot_animation.flr
    - assets/offline_animation.flr
    - assets/pulltosend_animation.flr
    - assets/transferfunds_illustration_start.svg
    - assets/transferfunds_illustration_start_paperwalletonly.svg
    - assets/transferfunds_illustration_start_kaliumwalletonly.svg
    - assets/transferfunds_illustration_end.svg
    - assets/transferfunds_illustration_end_paperwalletonly.svg
    - assets/transferfunds_illustration_end_kaliumwalletonly.svg

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
