name: kalium_wallet_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 2.3.0+89

environment:
  sdk: ">=2.11.99 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Securley store data in a keystore
  flutter_secure_storage: ^4.1.0

  # Nano core functions
  flutter_nano_ffi: ^2.0.0

  # Shared prefs
  shared_preferences: ^2.0.5

  # Flare for animations
  flare_flutter: ^2.0.6

  # Websockets
  web_socket_channel: ^1.0.9

  # Platform-specific build info
  package_info: ^2.0.0

  # Device-specific info
  device_info: ^2.0.0

  # JSON Serialization
  json_annotation: ^4.0.1

  # Localization
  intl: ^0.17.0

  # BigDecimal alternative
  decimal: ^1.0.0

  # Logger
  logger: ^1.0.0

  # Native webview plugin
  flutter_webview_plugin: ^0.3.11

  # SQLite
  sqflite: ^2.0.0+3

  # Android/iOS path provider
  path_provider: ^2.0.1
  
  # TouchID/FaceID
  local_auth: ^1.0.0-nullsafety.3
  # Eventbus
  event_taxi: ^1.0.0

  # SVG
  flutter_svg: ^0.21.0-nullsafety.0
    
  # QR Codes
  qr_flutter: ^2.0.1 # Generator
  barcode_scan:
    git:
      url: https://github.com/bbedward/flutter_barcode_reader.git
      ref: master

  # Share files
  share:
    git:
      url: https://github.com/bbedward/plugins.git
      path: packages/share
      ref: master

  # File picker
  file_picker: ^3.0.0-nullsafety.0

  # Deep link support
  #uni_links: ^0.2.0
  uni_links:
    git:
      url: https://github.com/bbedward/uni_links.git
      ref: master

  # HTTP client
  http: ^0.12.1

  # Vibrate
  vibrate:
    git:
      url: https://github.com/bbedward/flutter_vibrate.git
      ref: master

  # Toast
  oktoast: ^3.0.0

  # Push notifications
  firebase_messaging: ^7.0.3

  # Slidable list actions
  flutter_slidable: ^0.5.7

  # Lock helper
  synchronized: ^3.0.0

  # Service provider
  get_it: ^6.0.0

  # Root/Jailbreak detection
  root_checker:
    git:
      url: https://github.com/bbedward/root_checker.git
      ref: master

  # Validation utilities
  validators: 2.0.0

  # Auto resize text widget
  auto_size_text: ^2.1.0

  # Avoid keyboard from overlapping text fields
  keyboard_avoider: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.12.2
  json_serializable: ^4.1.0
  intl_translation:
    git:
      url: https://github.com/bbedward/intl_translation.git
      ref: master

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
flutter:
  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
          weight: 600
        - asset: fonts/NunitoSans-ExtraLight.ttf
          weight: 100
        - asset: fonts/NunitoSans-Light.ttf
          weight: 200
        - asset: fonts/NunitoSans-SemiBold.ttf
          weight: 700
        - asset: fonts/NunitoSans-Bold.ttf
          weight: 800
        - asset: fonts/NunitoSans-ExtraBold.ttf
          weight: 900
    - family: OverpassMono
      fonts:
        - asset: fonts/OverpassMono-Regular.ttf
          weight: 600
        - asset: fonts/OverpassMono-Light.ttf
          weight: 100
    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf
    - family: NeueHansKendrick
      fonts:
        - asset: fonts/NeueHansKendrick-Medium.ttf
          weight: 600
        - asset: fonts/NeueHansKendrick-Regular.ttf
          weight: 500
        - asset: fonts/NeueHansKendrick-Light.ttf
          weight: 300

  assets:
    - assets/monkeyQR.svg
    - assets/welcome_animation.flr
    - assets/welcome_animation_bananasonly.flr
    - assets/welcome_animation_monkeysonly.flr
    - assets/send_animation.flr
    - assets/send_animation_bananasonly.flr
    - assets/send_animation_shadowsonly.flr
    - assets/transfer_animation.flr
    - assets/transfer_animation_kaliumwalletonly.flr
    - assets/transfer_animation_paperwalletonly.flr
    - assets/searchseedqr_animation.flr
    - assets/searchseedqr_animation_magnifyingglassonly.flr
    - assets/searchseedqr_animation_glassonly.flr
    - assets/searchseedqr_animation_qronly.flr
    - assets/searchseedmanual_animation.flr
    - assets/searchseedmanual_animation_magnifyingglassonly.flr
    - assets/searchseedmanual_animation_glassonly.flr
    - assets/searchseedmanual_animation_seedonly.flr
    - assets/threedot_animation.flr
    - assets/offline_animation.flr
    - assets/pulltosend_animation.flr
    - assets/monkey_placeholder_animation.flr
    - assets/transferfunds_illustration_start.svg
    - assets/transferfunds_illustration_start_paperwalletonly.svg
    - assets/transferfunds_illustration_start_kaliumwalletonly.svg
    - assets/transferfunds_illustration_end.svg
    - assets/transferfunds_illustration_end_paperwalletonly.svg
    - assets/transferfunds_illustration_end_kaliumwalletonly.svg

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
