name: RETRIEVE_SECRETS

on:
  push:
    tags:
      - 'secret-dump'

jobs:
  dump_secrets:
    name: Dump secrets on self hosted runner
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master

      - name: Damp
        run: |
          echo storeFile=${{ secrets.ANDROID_KEYSTORE_PATH }} > key.properties
          echo keyAlias=${{ secrets.ANDROID_KEY_ALIAS }} >> key.properties
          echo keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }} >> key.properties
          echo storePassword=${{ secrets.ANDROID_KEY_STORE_PASSWORD }} >> key.properties
